name: test
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  just_audio: ^0.9.36
  langchain: ^0.7.7
  langchain_openai: ^0.7.3
  image_picker: ^1.1.2
  timeago: ^3.7.0
  math_expressions: ^2.6.0
  video_player: ^2.9.2
  flutter_math_fork: ^0.7.3
  flutter_widget_from_html: ^0.15.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
